version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.20.2
    - 5.21.2
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: react-hook-form
    versions:
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.6
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
    - 7.3.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.8
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: "@hookform/resolvers"
    versions:
    - 1.3.5
    - 1.3.6
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.2.1
    - 3.8.0
    - 3.9.0
    - 3.9.2
    - 4.0.0
    - 4.0.2
    - 4.0.3
  - dependency-name: next-seo
    versions:
    - 4.21.0
    - 4.22.0
    - 4.23.0
  - dependency-name: next-sitemap
    versions:
    - 1.6.3
    - 1.6.9
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.8.0
  - dependency-name: "@types/jsonwebtoken"
    versions:
    - 8.5.1
  - dependency-name: "@types/relay-runtime"
    versions:
    - 10.1.10
    - 10.1.9
  - dependency-name: next-google-fonts
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.13.8
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.8
  - dependency-name: got
    versions:
    - 11.8.2
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.1
    - 5.2.2
    - 5.3.0
  - dependency-name: "@babel/node"
    versions:
    - 7.12.17
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
  - dependency-name: babel-plugin-inline-react-svg
    versions:
    - 2.0.0
  - dependency-name: mongoose
    versions:
    - 5.11.15
    - 5.11.17
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.26
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
  - dependency-name: "@chakra-ui/icons"
    versions:
    - 1.0.5
  - dependency-name: "@emotion/react"
    versions:
    - 11.1.4
    - 11.1.5
  - dependency-name: "@chakra-ui/react"
    versions:
    - 1.3.2
  - dependency-name: xstate
    versions:
    - 4.16.2
  - dependency-name: "@chakra-ui/layout"
    versions:
    - 1.3.1
  - dependency-name: "@emotion/styled"
    versions:
    - 11.1.5
  - dependency-name: react-icons
    versions:
    - 4.2.0
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: relay-hooks
    versions:
    - 4.1.0
  - dependency-name: rss-parser
    versions:
    - 3.11.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: react-relay
    versions:
    - 10.1.3
  - dependency-name: webpack-plugin-serve
    versions:
    - 1.2.1
