import { IPlans } from "src/modules/Landing/Sponsorship/Plans/Plans.types";

const plans: IPlans = [
  {
    category: "All",
    price: 499,
    available: 5,
    taps: 1800,
    subscriptions: 200,
  },
  {
    category: "Arts",
    price: 250,
    available: 5,
    taps: 900,
    subscriptions: 100,
  },
  {
    category: "Business",
    price: 499,
    available: 5,
    taps: 1600,
    subscriptions: 200,
  },
  {
    category: "Comedy",
    price: 250,
    available: 5,
    taps: 730,
    subscriptions: 60,
  },
  {
    category: "Education",
    price: 200,
    available: 5,
    taps: 400,
    subscriptions: 55,
  },
  {
    category: "Fiction",
    price: 150,
    available: 5,
    taps: 230,
    subscriptions: 25,
  },
  {
    category: "Government",
    price: 120,
    available: 5,
    taps: 160,
    subscriptions: 30,
  },
  {
    category: "Health & Fitness",
    price: 320,
    available: 5,
    taps: 820,
    subscriptions: 90,
  },
  {
    category: "History",
    price: 300,
    available: 5,
    taps: 690,
    subscriptions: 65,
  },
  {
    category: "Kids & Family",
    price: 120,
    available: 5,
    taps: 210,
    subscriptions: 35,
  },
  {
    category: "Leisure",
    price: 150,
    available: 5,
    taps: 350,
    subscriptions: 45,
  },
  {
    category: "Music",
    price: 150,
    available: 5,
    taps: 430,
    subscriptions: 50,
  },
  {
    category: "News",
    price: 499,
    available: 5,
    taps: 1600,
    subscriptions: 170,
  },
  {
    category: "Religion & Spirituality",
    price: 250,
    available: 5,
    taps: 450,
    subscriptions: 35,
  },
  {
    category: "Science",
    price: 250,
    available: 5,
    taps: 920,
    subscriptions: 85,
  },
  {
    category: "Society & Culture",
    price: 499,
    available: 5,
    taps: 1600,
    subscriptions: 155,
  },
  {
    category: "Sports",
    price: 150,
    available: 5,
    taps: 880,
    subscriptions: 75,
  },
  {
    category: "TV & Film",
    price: 300,
    available: 5,
    taps: 500,
    subscriptions: 45,
  },
  {
    category: "Technology",
    price: 3500,
    available: 5,
    taps: 900,
    subscriptions: 75,
  },
  {
    category: "True Crime",
    price: 150,
    available: 5,
    taps: 650,
    subscriptions: 55,
  },
];

export default plans;
